### ISSUE TITLE
BundleCache not used if missing images in stylesheet or using external scripts

### ISSUE THREAD

**Issue by nazjunaid** [andrewdavey/cassette#142]
Related to Issues #55 and #57

We have noticed a large amount of filelocking errors on our production servers during application recycle or config changing which appear to be happening during cassette initialization.

```
Server stack trace: 
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath)
   at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, IsolatedStorageFile isf)
   at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, IsolatedStorageFile isf)
   at System.IO.IsolatedStorage.IsolatedStorageFile.OpenFile(String path, FileMode mode, FileAccess access, FileShare share)
   at Cassette.IO.IsolatedStorageFileWrapper.Open(FileMode mode, FileAccess access, FileShare fileShare) in C:\Websites\Git\cassette\src\Cassette\IO\IsolatedStorageFileSystem.cs:line 32
   at Cassette.Persistence.ModuleCache`1.SaveModule(T module) in C:\Websites\Git\cassette\src\Cassette\Persistence\ModuleCache.cs:line 247
   at Cassette.Persistence.ModuleCache`1.SaveModuleContainer(IModuleContainer`1 moduleContainer) in C:\Websites\Git\cassette\src\Cassette\Persistence\ModuleCache.cs:line 164
   at Cassette.ModuleConfiguration.GetOrCreateCachedModuleContainer[T](T[] modules) in C:\Websites\Git\cassette\src\Cassette\ModuleConfiguration.cs:line 104
   at Cassette.ModuleConfiguration.CreateModuleContainer[T](Boolean useCache) in C:\Websites\Git\cassette\src\Cassette\ModuleConfiguration.cs:line 85
   at Cassette.ModuleConfiguration.<>c__DisplayClass3.<CreateModuleContainers>b__1(KeyValuePair`2 kvp) in C:\Websites\Git\cassette\src\Cassette\ModuleConfiguration.cs:line 75
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElem
```

After debugging the issue locally I think it could be because of a bug where the BundleCache isn't being used in our application due to missing images referenced in styleheets which trip up this check in the FilesAreUpToDate method.

```
if (files.Any(f => !f.Exists)) return false;
```

The files array appears to include references to the missing images so this check always returns false and cassette goes through the costly initialization procedure every time.

As a work around I modified the ExpandCssUrlsAssetTransformer and removed the following check.

```
if (!file.Exists) return;
```

This now means cassette throws exception but only in debug=false configuration if a reference to an image is not there which isn't ideal.

Ideally I think the caching mechanism would just ignore the broken references.

**Comment by nazjunaid** [comment]
There appears to be another issue with our application after adding the missing images we are still failing to InitializeBundlesFromCacheIfUpToDate and this time the following check

```
if (bundleInitializationActions.Any(c => c == null)) return false;
```

There appears to be about 5 actions in that list that are null due to the GetHash call in CreateBundleInitializationAction returning null on external scripts which also means BundleCache is never used if you use External Scripts in your application.

**Comment by andrewdavey** [comment]
The bundle cache behaviour when there are external bundles is certainly broken. I saw this recently in my own projects. I'm in the process of rewriting the bundle cache code. This will fix the external bundles issue.

I'll have to give some thought to the correct way to treat missing image files. I don't know if the cache can simply ignore missing files. Deleting an asset file (e.g. a stylesheet) certainly requires a re-build of the cache. Deleting a "raw file", like an image, would usually coincide with the stylesheet being modified, also triggering a cache re-build.

Perhaps Cassette should track the "does-not-exist" status of raw files in the cache manifest.

The cache-validation logic could also have different behaviour for assets vs raw-files.

**Comment by nazjunaid** [comment]
My workaround didn't appear work, broke cassette in rendering external scripts. 

I will have to wait for your re-write of the bundle cache.

**Comment by nazjunaid** [comment]
This issue appears to be a lot more severe then I initially thought because the BundleCache never gets initialized correctly and the assignCachedAsset doesn't run so for every request the application is Minifying Javscript on the fly.

**Comment by andrewdavey** [comment]
I've made good progress on the new bundle caching code today. I should have something for you to try out tomorrow.

**Comment by andrewdavey** [comment]
`master` now contains the latest work to improve the bundle caching. I've not addressed the missing image file issue yet, but the new code should be easier to build on.

**Comment by nazjunaid** [comment]
Nice work! Shall have a play around tomorrow.

**Comment by andrewdavey** [comment]
Okay, thanks. Let me know how you get on.

I think simply not calling `asset.AddRawFileReference(relativeFilename);` in `ExpandCssUrlsAssetTransformer` when the file does not exist may be enough to solve your issue.

**Comment by nazjunaid** [comment]
Sorry I'm still having issues I initially thought it was to do with Encoding but now I think it's something else I will investigate further and see what's going on.

**Comment by nazjunaid** [comment]
I've narrowed down the problem to having a Bundle with 22 assets but the assets appear to be in a different order when comparing the cachedManifest with the currentManifest so the `Assets.SequenceEqual(assets);` check failed in BundleManifest.

**Comment by nazjunaid** [comment]
I've not been able to figure out why the assets are in a different order but I've managed to work around the issue and get the caching working with this hack.

```
bool AssetsEqual(IEnumerable<AssetManifest> assets)
{
    return Assets.OrderBy(x => x.Path).SequenceEqual(assets.OrderBy(x => x.Path));
}
```

**Comment by andrewdavey** [comment]
It's the cached manifest was built from processed bundles. Processed bundles have their assets sorted by dependencies. This meant the order was different compared to the unprocessed bundles.

The above commit should fix this issue by ordering the assets (and also bundle) manifests by path, as per your suggestion.

**Comment by nazjunaid** [comment]
Just like to confirm most of the issues are fixed however we still have the issue with the cache not being used if there are missing images in the stylesheet

**Comment by andrewdavey** [comment]
Okay, yes that's still to be fixed. It's next on my list :)

**Comment by nazjunaid** [comment]
It's all peachy, Thanks!
