### ISSUE TITLE
CreateBundles task throwing SerializationException

### ISSUE THREAD

**Issue by ghost** [andrewdavey/cassette#237]
I'm totally new to Cassette, and so I installed a bunch of packages via NuGet, including:

```
Cassette (1.2.1)
Cassette.MSBuild (1.2.1)
Cassette.Web (1.2.1)
Cassette.Web.Jasmine (1.2.1)
SassAndCoffee.Core (2.0.2.0)
jQuery (1.7.2)
Twitter.Bootstrap (2.0.2)
```

However, when I try to do a build on a basic ASP .NET MVC 4 project, I get the following error:

The "CreateBundles" task failed unexpectedly.
System.Runtime.Serialization.SerializationException: Type 'Cassette.Stylesheets.LessCompileException' in assembly 'Cassette, Version=1.2.1.30492, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
   at Microsoft.Build.Framework.ITask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__1c.MoveNext() Sandbox

I verified that the cassette .dll I am referencing is the correct version.

Any ideas?

Thanks!

Josh

**Comment by ghost** [comment]
I went ahead and uninstalled the Cassette.MSBuild package and I can now successfully build my application.
