### ISSUE TITLE
v2 error when attempting to rebuild the bundle cache

### ISSUE THREAD

**Issue by willholley** [andrewdavey/cassette#267]
In IIS 7.5, when attempting to rebuild the bundle cache, cassette hangs. The error in the Windows event log is:

 Exception type: LockRecursionException
    Exception message: Recursive write lock acquisitions not allowed in this mode.
   at System.Threading.ReaderWriterLockSlim.TryEnterWriteLockCore(Int32 millisecondsTimeout)
   at System.Threading.ReaderWriterLockSlim.TryEnterWriteLock(Int32 millisecondsTimeout)
   at Cassette.BundleCollection.set_InitializationException(Exception value)
   at Cassette.ExceptionCatchingBundleCollectionInitializer.Initialize(BundleCollection bundleCollection)
   at Cassette.Aspnet.DiagnosticRequestHandler.RebuildCache()
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by andrewdavey** [comment]
Thanks for catching that. I'll look into it ASAP.
