### ISSUE TITLE
 cassette-cache manifest.xml changes after deployment

### ISSUE THREAD

**Issue by dotnetchris** [andrewdavey/cassette#306]
Also my release time seems to be faster, but it still seemed like it was doing some kind of compilation or validation or something that would increase start up time.

``` C#
System.Exception: Bundle collection rebuild failed. See inner exception for details. ---> System.UnauthorizedAccessException: Access to the path 'C:\inetpub\wwwroot\Content\cassette-cache\manifest.xml' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Cassette.IO.FileSystemFile.Open(FileMode mode, FileAccess access, FileShare fileShare)
   at Cassette.Caching.BundleCollectionCacheWriter.WriteManifestFile(Manifest manifest)
   at Cassette.Caching.BundleCollectionCache.Write(Manifest manifest)
   at Cassette.CacheAwareBundleCollectionInitializer.WriteToCache()
   at Cassette.CacheAwareBundleCollectionInitializer.Initialize(BundleCollection bundleCollection)
   at Cassette.ExceptionCatchingBundleCollectionInitializer.Initialize(BundleCollection bundleCollection)
   --- End of inner exception stack trace ---
   at Cassette.BundleCollection.GetReadLock()
   at Cassette.ReferenceBuilder.Reference(Bundle bundle, String location)
   at Ritter.AgentManagement.Web.UI.Infrastructure.ViewConfiguration.ViewModelConfigInjectionActionFilter.OnActionExecuted(ActionExecutedContext filterContext)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)
   at System.Web.Mvc.Controller.ExecuteCore()
   at System.Web.Mvc.ControllerBase.Execute(RequestContext requestContext)
   at System.Web.Mvc.MvcHandler.<>c__DisplayClass6.<>c__DisplayClassb.<BeginProcessRequest>b__5()
   at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass1.<MakeVoidDelegate>b__0()
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

One random thing i see in here that's likely unrelated Cassette.BundleCollection.GetReadLock() i sure hope you don't need to lock anything for every read. You likely shouldn't need to lock anything for read at all ever if you use the interlocked classes properly for lockless code.

**Comment by SLaks** [comment]
The GetReadLock method sounds like a reader-writer lock, which doesn't block unless writing is involved.

**Comment by andrewdavey** [comment]
Can you check the start up trace in /cassette.axd? It looks like you're not actually hitting the static cache.

https://github.com/andrewdavey/cassette/blob/master/src/Cassette/CacheAwareBundleCollectionInitializer.cs#L25 should never call WriteCache for static cache.

**Comment by andrewdavey** [comment]
BundleCollection uses a ReaderWriterLockSlim https://github.com/andrewdavey/cassette/blob/master/src/Cassette/BundleCollection.cs#L23 which I assume is fast.

The read lock is required because otherwise you'd be potentially reading a partially modified collection while it's being updated.

**Comment by dotnetchris** [comment]
``` C#
Cassette Information: 0 : Running start-up task: Cassette.Views.BundlesHelper
Cassette Information: 0 : Initializing Bundles helper
Cassette Information: 0 : Running start-up task: Cassette.FileSystemWatchingBundleRebuilder
Cassette Information: 0 : CacheAwareBundleCollectionInitializer.ClearBundles
Cassette Information: 0 : CacheAwareBundleCollectionInitializer.ReadCache
Cassette Information: 0 : CacheAwareBundleCollectionInitializer using static cache
Cassette Information: 0 : CacheAwareBundleCollectionInitializer.UseCacheBundles
Cassette Information: 0 : CacheAwareBundleCollectionInitializer.ClearBundles
Cassette Information: 0 : Total time elapsed: 2445ms
```

**Comment by andrewdavey** [comment]
Okay, thanks for confirming. My guess is that the static cache is being used at app start. However, somehow the bundle collection initializer is getting called again later and with a non-static cache.

I'll need to dig into this some more...

**Comment by dotnetchris** [comment]
Is there anything I can provide that might help more? Like the content of the manifest or anything?

**Comment by andrewdavey** [comment]
I've not been able to reproduce this yet. Please email me the manifest file as it appears directly after building, and then after the application has run (and somehow overwritten it).

Can you also confirm that the `<cassette cacheDirectory="..." />` is correctly set in web.config?

**Comment by andrewdavey** [comment]
Could any other part of your application be altering the contents of Cassette cache directory? File system changes would trigger the bundle collection initializer. If those changes somehow broke the manifest or bundle data, then an exception would be thrown and Cassette discards the invalid cache. (This edge case needs some tracing added!)

**Comment by dotnetchris** [comment]
No nothing in my app touches that folder. My best guess is it's related to how web deploy uploads the files. I don't think cassette should invalidate the cache on file changes. If i deploy static resources it should load them once at app start and never for any reason do anything else.

**Comment by andrewdavey** [comment]
I suppose deployment could confuse things. Copying files into a site while it's running would certainly trigger Cassette's file system watcher.

We should disable the file system watcher when a static cache is present. This will prevent the bundle collection initializer from being triggered.

**Comment by andrewdavey** [comment]
I've pushed v2.0.1-alpha2 to nuget. It includes the above commit which disables file system watching when cache manifest is static.

**Comment by dotnetchris** [comment]
I'll pull that down.

**Comment by dotnetchris** [comment]
Remove write perms to cassette-cache in production and deployed, and app is online.

**Comment by jpsullivan** [comment]
Would someone kindly explain how they are getting that trace data from cassette.axd?  I've enabled tracing and have tried viewing the trace.axd list, but nothing seems to show.

I'm currently dealing with the same problem (same exception, at least) and cannot seem to make any progress on this.  I'm running on .NET 3.5 if that helps at all.

**Comment by elerch** [comment]
The trace above (https://github.com/andrewdavey/cassette/issues/306#issuecomment-8190868) is not in trace.axd.  If you go to cassette.axd directly there is a startup trace tab where the information will show up (assuming that you've configured web.config properly)

**Comment by jpsullivan** [comment]
Thanks for the quick response!

Unfortunately, it seems like my application is failing before it even reaches cassette.axd.  Oddly enough, this works perfectly when when running from Visual Studio on root (i.e., localhost:4771) but as soon as I change it to run on localhost/myapp it starts showing these "access to path ### is denied" errors.

I'll keep digging around and see if I can manage to find what is happening here...

Thanks again!

**Comment by andrewdavey** [comment]
Check that the user IIS is running the app pool under has access to the
files.
