### ISSUE TITLE
Cassette 9.1 breaks when I update to AjaxMin 4.30.xxxx (latest)

### ISSUE THREAD

**Issue by kekonn** [andrewdavey/cassette#99]
This is the exception I get: 

System.IO.FileLoadException was unhandled by user code
     Message=Could not load file or assembly 'AjaxMin, Version=4.19.4141.18463, Culture=neutral, PublicKeyToken=24297a69a7eae424' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   Source=Cassette
  FileName=AjaxMin, Version=4.19.4141.18463, Culture=neutral, PublicKeyToken=24297a69a7eae424
   FusionLog==== Pre-bind state information ===
    LOG: User = ATOMIUM\JVDAI54
    LOG: DisplayName = AjaxMin, Version=4.19.4141.18463, Culture=neutral, PublicKeyToken=24297a69a7eae424
 (Fully-specified)
    LOG: Appbase = file:///C:/tmp/addict/TimBartJonasCV/RealDolmen.Acaddemict.CV/RealDolmen.Acaddemict.CV.Web/
    LOG: Initial PrivatePath = C:\tmp\addict\TimBartJonasCV\RealDolmen.Acaddemict.CV\RealDolmen.Acaddemict.CV.Web\bin
Calling assembly : Cassette, Version=0.9.1.0, Culture=neutral, PublicKeyToken=null.
    ===
    LOG: This bind starts in default load context.
    LOG: Using application configuration file: C:\tmp\addict\TimBartJonasCV\RealDolmen.Acaddemict.CV\RealDolmen.Acaddemict.CV.Web\web.config
    LOG: Using host configuration file: C:\Users\JVDAI54\Documents\IISExpress\config\aspnet.config
    LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
    LOG: Post-policy reference: AjaxMin, Version=4.19.4141.18463, Culture=neutral, PublicKeyToken=24297a69a7eae424
    LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/Temporary ASP.NET Files/root/88aa44b0/fbbd264d/AjaxMin.DLL.
    LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/Temporary ASP.NET Files/root/88aa44b0/fbbd264d/AjaxMin/AjaxMin.DLL.
    LOG: Attempting download of new URL file:///C:/tmp/addict/TimBartJonasCV/RealDolmen.Acaddemict.CV/RealDolmen.Acaddemict.CV.Web/bin/AjaxMin.DLL.
    WRN: Comparing the assembly name resulted in the mismatch: Minor Version
    ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

  StackTrace:
       at Cassette.Stylesheets.MicrosoftStyleSheetMinifier..ctor()
       at Cassette.Stylesheets.StylesheetPipeline..ctor()
       at Cassette.Stylesheets.StylesheetBundle..ctor(String applicationRelativePath)
       at Cassette.Stylesheets.StylesheetBundleFactory.CreateBundleCore(String path, BundleDescriptor bundleDescriptor)
       at Cassette.BundleFactoryBase`1.CreateBundle(String path, IEnumerable`1 allFiles, BundleDescriptor bundleDescriptor)
       at Cassette.Configuration.BundleCollectionExtensions.AddPerIndividualFile[T](BundleCollection bundleCollection, String directoryPath, IFileSearch fileSearch, Action`1 customizeBundle)
       at RealDolmen.Acaddemict.CV.Web.CassetteConfiguration.Configure(BundleCollection bundles, CassetteSettings settings) in C:\tmp\addict\TimBartJonasCV\RealDolmen.Acaddemict.CV\RealDolmen.Acaddemict.CV.Web\CassetteConfiguration.cs:line 20
       at Cassette.Web.StartUp.CreateCassetteApplication()
       at Cassette.CassetteApplicationContainer`1.CreateApplication()
  InnerException:

**Comment by andrewdavey** [comment]
v0.9.2 is now in nuget and depends on the latest AjaxMin 4.30.

**Comment by kekonn** [comment]
Confirmed as fixed
